export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs";
import { GoogleGenerativeAI } from "@google/generative-ai";

export async function POST(req: NextRequest) {
  try {
    const { userId } = auth();
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();
    const { action, prompt, imageBase64, mimeType } = body;

    const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
    if (!GEMINI_API_KEY) {
      return NextResponse.json(
        { error: "Gemini API key not configured. Add GEMINI_API_KEY to .env.local" },
        { status: 500 }
      );
    }

    // Initialize Gemini SDK
    const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);

    // ─── TEXT TO IMAGE ─────────────────────────────────────────────────────
    if (action === "text-to-image") {
      try {
        // Try Imagen 3 first
        const imageModel = genAI.getGenerativeModel({ model: "imagen-3.0-generate-002" });
        const imageResult = await (imageModel as any).generateImages({
          prompt,
          number_of_images: 1,
          aspect_ratio: "1:1",
        });

        const imageData = imageResult?.generatedImages?.[0]?.image?.imageBytes;
        if (imageData) {
          return NextResponse.json({
            type: "image",
            imageBase64: imageData,
            mimeType: "image/png",
          });
        }
      } catch (imagenError) {
        // Imagen not available — fallback to Gemini Flash description
        console.log("Imagen not available, using Gemini Flash fallback");
      }

      // Fallback: Use Gemini Flash to describe the image concept
      const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
      const result = await model.generateContent([
        `You are a creative AI image generator assistant. 
        The user wants to generate an image with this prompt: "${prompt}".
        
        Please provide:
        1. A vivid, detailed description of what this generated image would look like (4-5 sentences)
        2. The mood and atmosphere of the image
        3. Color palette that would dominate
        4. Three alternative/improved prompts the user can try for better results
        
        Format your response clearly with these sections labeled.`,
      ]);

      const description = result.response.text();
      return NextResponse.json({
        type: "description",
        description,
        message: "Image concept generated by Gemini AI",
      });
    }

    // ─── IMAGE ANALYSIS ────────────────────────────────────────────────────
    if (action === "analyze-image") {
      if (!imageBase64) {
        return NextResponse.json({ error: "No image provided" }, { status: 400 });
      }

      const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

      const imagePart = {
        inlineData: {
          data: imageBase64,
          mimeType: mimeType || "image/jpeg",
        },
      };

      const result = await model.generateContent([
        imagePart,
        `Analyze this image in detail and provide a comprehensive report:

1. 📸 **Overall Description** — What is this image about? (2-3 sentences)
2. 🎯 **Main Subject** — What is the primary subject or focus?
3. 🌈 **Colors & Mood** — Describe dominant colors and overall mood/atmosphere
4. 📍 **Setting/Background** — Where does this appear to be taken?
5. 🔍 **Key Objects** — List all main objects or elements visible
6. 💡 **Interesting Details** — Any unique or notable details worth mentioning
7. 🎨 **Photography/Art Style** — Type of shot, lighting, angle, art style
8. ⭐ **Quality Rating** — Rate image quality from 1-10 and explain why
9. 🏷️ **Tags** — List 8-10 relevant tags for this image

Please format clearly with these sections.`,
      ]);

      const analysis = result.response.text();
      return NextResponse.json({ analysis });
    }

    return NextResponse.json({ error: "Invalid action" }, { status: 400 });

  } catch (error: any) {
    console.error("Gemini API error:", error);
    return NextResponse.json(
      { error: error.message || "Something went wrong" },
      { status: 500 }
    );
  }
}